/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

/**
 *
 * @author Jonas
 */
public class MoCr_Frame_Credits extends javax.swing.JFrame {

    /**
     * Creates new form MoCr_Frame_Credits
     */
    public MoCr_Frame_Credits() {
        initComponents();
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        MoCr_Credits_TextArea = new javax.swing.JTextArea();

        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        MoCr_Credits_TextArea.setEditable(false);
        MoCr_Credits_TextArea.setColumns(20);
        MoCr_Credits_TextArea.setFont(new java.awt.Font("Constantia", 0, 13)); // NOI18N
        MoCr_Credits_TextArea.setRows(5);
        MoCr_Credits_TextArea.setText("Dieses Applet wurde im Rahmen des\nP-Seminars Softwareprojekts am\nNikolaus-Kopernikus-Gymnasiums Weißenhorn\nerstellt.\n\nCoding:\tGUI:\tDesign:\nCaterina C.\tSimon S.\tClemens S.\nMatthias G.\tJonas M.\n\nPartner: Fachschaft Mathematik\nKontaktperson: S. Breins\n\n\n");
        jScrollPane1.setViewportView(MoCr_Credits_TextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea MoCr_Credits_TextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
