/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;
import tools.TxtAmbassador;
import core.WindowLogic;
/**
 *
 * @author Jonas
 */
public class MoCr_Frame_Support extends javax.swing.JFrame {

    public static TxtAmbassador Inserter = new TxtAmbassador();
    /**
     * Creates new form MoCr_Frame_Support
     */
    public MoCr_Frame_Support() {
        initComponents();
    }
    
    public void refreshSupport() {
        Inserter.readSupTxt(MoCr_Frame_Support_Area, WindowLogic.getInstance().getencryptionType(), WindowLogic.getInstance().getChiffrestate());       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MoCr_Frame_Support_Area = new javax.swing.JTextArea();

        setTitle("MonkeyCrypt - Hilfsfenster");
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hilfe");

        MoCr_Frame_Support_Area.setEditable(false);
        MoCr_Frame_Support_Area.setColumns(20);
        MoCr_Frame_Support_Area.setLineWrap(true);
        MoCr_Frame_Support_Area.setRows(5);
        MoCr_Frame_Support_Area.setWrapStyleWord(true);
        jScrollPane1.setViewportView(MoCr_Frame_Support_Area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea MoCr_Frame_Support_Area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
